### ISSUE TITLE
Issue with mpirun on thiophene

### ISSUE THREAD

**Issue by sli259** [hema-ted/pycdft#2]
Hi, I am trying to use your code on thiophene dimer with mpirun, but I got the following error at the initial qb step, but there was no problem while I tested on the He2 example. Do you have any suggestions why this happen? I attached the align.in file below. It is the same file provided in the directory, I just replaced the variables with your code. 

Thank you!

(base) $ mpirun -np 2 qb < align.in > align.out
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node tnxt-0469 exited on signal 9 (Killed).

### align.in###
set cell     47.243149714473084    0.0    0.0    0.0    47.243149714473084    0.0    0.0    0.0    56.691779657367704

species H H_ONCV_PBE-1.0.xml
species C C_ONCV_PBE-1.0.xml
species S S_ONCV_PBE-1.0.xml

atom    H1    H    8.882798738764373    5.742357604644488    8.955325451492634e-16
atom    H2    H    5.116952788724296    8.702046447956798    8.461696591310609e-16
atom    H3    H    7.550163971618516    1.1677561746423457    5.338186501170295e-16
atom    H4    H    0.9869566406850583    6.326282935115376    4.478067718950874e-16
atom    H5    H    8.882798738764373    5.742357604644488    6.614040961
atom    H6    H    5.116952788724296    8.702046447956798    6.614040961
atom    H7    H    7.550163971618516    1.1677561746423457    6.614040961
atom    H8    H    0.9869566406850583    6.326282935115376    6.614040961
atom    C1    C    7.043339461481649    5.154841794795302    7.469231815459404e-16
atom    C2    C    4.980892517546612    6.775848747798301    7.198927779504126e-16
atom    C3    C    6.299354339778128    2.636214997217313    5.471458193555351e-16
atom    C4    C    2.7093001498256033    5.457953843363361    5.001000730291152e-16
atom    C5    C    7.043339461481649    5.154841794795302    6.614040961
atom    C6    C    4.980892517546612    6.775848747798301    6.614040961
atom    C7    C    6.299354339778128    2.636214997217313    6.614040961
atom    C8    C    2.7093001498256033    5.457953843363361    6.614040961
atom    S1    S    3.0543168721903995    2.2023339102395916    3.2187702774691594e-16
atom    S2    S    3.0543168721903995    2.2023339102395916    6.614040961

set net_charge 1
set nspin 2
set xc PBE
set ecut 40
set wf_dyn JD
set scf_tol 1.0E-8

randomize_wf

run 0 200 5

save gs.xml

**Comment by wwwennie** [comment]
Hello, 
This is often an mpirun error relating to memory, e.g., OOM.  The thiophene dimer is quite a bit bigger than He2+ and the required memory may exceed that which is available on your 2 requested processes. I recommend trying to request at least a few tens of processes or request more memory per process.

**Comment by sli259** [comment]
@wwwennie 
Thank you! More np works. I have another question to ask: I believe I need the *.xml files for this code, right? Are those generated by the oncvpsp? I tried to compiled it on the cluster but having this error that I don't know where goes wrong. Would you mind to take a look and give me some suggestion?
gfortran -O3 -ffast-math -funroll-loops -I/sw/eb/sw/libxc/4.3.4-GCC-8.3.0/include  -o functionals.o -c functionals_cpp.f90
gfortran -O3 -ffast-math -funroll-loops -I/sw/eb/sw/libxc/4.3.4-GCC-8.3.0/include  -c exc_libxc.f90
gfortran -o oncvpsp.x oncvpsp.o fphsft.o fpovlp.o gnu_script.o linout.o psatom.o relatom.o run_config.o run_diag.o run_phsft.o run_plot.o run_vkb.o sratom.o upfout.o wellstate.o aeo.o check_data.o const_basis.o dpnint.o eresid.o exchdl.o exc_off_pbe.o excpzca.o excwig.o ldiracfb.o ldiracfs.o lschfb.o lschfs.o lschkb.o lschpb.o lschpse.o lschps.o lschvkbbe.o lschvkbb.o lschvkbs.o modcore.o optimize.o pspot.o qroots.o run_optimize.o sbf8.o sbf_basis.o sbf_rc_der.o tfapot.o vkboutwf.o vkbphsft.o vout.o vpinteg.o vploc.o wf_rc_der.o modcore2.o gg1cc.o gp1cc.o gpp1cc.o der2exc.o modcore3.o old_optimize.o run_ghosts.o lschpsbar.o functionals.o exc_libxc.o  -L/scratch/user/sli259/source/math/lib -llapack -lrefblas -L/sw/eb/sw/libxc/4.3.4-GCC-8.3.0/lib64 -lxcf90 -lxc
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_get_vxc: error: undefined reference to 'xc_f90_mgga_x_tb09_set_par_'
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_load: error: undefined reference to 'xc_f90_lda_c_xalpha_set_par_'
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_copy: error: undefined reference to 'xc_f90_lda_c_xalpha_set_par_'
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_init: error: undefined reference to 'xc_f90_lda_x_set_par_'
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_init: error: undefined reference to 'xc_f90_lda_c_xalpha_set_par_'
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_load: error: undefined reference to 'xc_f90_lda_x_set_par_'
functionals.o:functionals_cpp.f90:function __functionals_m_MOD_functional_copy: error: undefined reference to 'xc_f90_lda_x_set_par_'
collect2: error: ld returned 1 exit status
make[1]: *** [oncvpsp] Error 1

#######
I basically edit the make.inc file to change the path to libxc and lacpack etc.  Here is the content in the make.inc file. 

##### Edit the following lines to correspond to your compilers ####

F77        = gfortran
F90        = gfortran
CC         = gcc
FCCPP      = cpp

FLINKER     = $(F90)

FCCPPFLAGS = -ansi -DLIBXC_VERSION=203  #This probably should not be changed

##### Edit the following optimization flags for your system ####

FFLAGS     = -O3 -ffast-math -funroll-loops
CFLAGS     = -O3

##### Edit the following LAPACK and BLAS library paths for your system ####

LIBS = -L/scratch/user/sli259/source/math/lib -llapack -lrefblas

##### Edit the following for to use libxc if available #####

OBJS_LIBXC =    exc_libxc_stub.o

# oncvpsp is compatible with libxc
# To build oncvpsp with libxc, uncomment 3 of the following lines and edit
# the paths to point to your libxc library and include directories
# make clean in src before rebuilding after changing this

##for libxc 2.1.0 and later use
LIBS += -L/sw/eb/sw/libxc/4.3.4-GCC-8.3.0/lib64 -lxcf90 -lxc

##for earlier releases use
#LIBS += -L/home/drh/abinit/fallbacks/exports/lib -lxc

FFLAGS += -I/sw/eb/sw/libxc/4.3.4-GCC-8.3.0/include
OBJS_LIBXC =    functionals.o exc_libxc.o

**Comment by wwwennie** [comment]
Hello,
If you need to generate your own pseudopotentials, then you would need to compile oncvpsp. For compiling questions related to oncvpsp, please refer to their documentation/forums. 
Otherwise it is recommended to use the generated ONCV pseudopotentials from the SG15 database, as used in the paper.
The *xml files are generated from the qbox code (http://qboxcode.org/build/).

**Comment by sli259** [comment]
@wwwennie 
Thanks for your answering, I was able to complete the tutorial with thiophene you provided and there was no problem. However, I tried to make my own molecular dimers and calculated the electronic coupling, the initial GS calculation went through, I then edit the python code for the solver1 and solver2 calculation. I got an error about missing the "qb_cdft.in.lock" file. 
I noticed that this file was generated during the calculation, but somehow deleted as the calculation proceed. I don't have this error for the thiophene example or He2+. I am wondering if you have a solution for this, or let me know what I missed for my system setup. 
One of the difference of my set up is I used an xyz file for the ase.read, instead of the cif file as used in your example, I don't know if this causing a difference since there is no cell information. I added a cell.center(5) in the code to generate cell. Not sure it this is the issue. I am also running this on a cluster with 12 cores, this is part of the error message:

<release> 1.67.4 centos7  </release>
<sysname> Linux </sysname>
<nodename> tnxt-0469.cluster </nodename>
<start_time> 2020-11-03T14:44:13Z </start_time>
<mpi_processes count="1">
<process id="0"> tnxt-0469.cluster </process>
</mpi_processes>
Traceback (most recent call last):
  File "/scratch/user/sli259/ASE/PyCDFT/pycdft/pycdft/cdft.py", line 77, in solve
    self.dft_driver.get_rho_r()
  File "/scratch/user/sli259/ASE/PyCDFT/pycdft/pycdft/dft_driver/qbox_driver.py", line 147, in get_rho_r
    self.run_cmd(cmd="plot -density {} {}".format(
  File "/scratch/user/sli259/ASE/PyCDFT/pycdft/pycdft/dft_driver/qbox_driver.py", line 85, in run_cmd
    os.remove(self.lock_file)
FileNotFoundError: [Errno 2] No such file or directory: 'qb_cdft.in.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "3.5-benz-coupling.py", line 61, in <module>

  File "/scratch/user/sli259/ASE/PyCDFT/pycdft/pycdft/cdft.py", line 86, in solve
    self.dft_driver.exit()
  File "/scratch/user/sli259/ASE/PyCDFT/pycdft/pycdft/dft_driver/qbox_driver.py", line 315, in exit
    os.remove(self.lock_file)
FileNotFoundError: [Errno 2] No such file or directory: 'qb_cdft.in.lock'
<real_time> 1556.909 </real_time>
<end_time> 2020-11-03T15:10:09Z </end_time>
</fpmd:simulation>

**Comment by wwwennie** [comment]
Hello, 
The "qb_cdft.in.lock" file is created by the qbox code; its removal is used to indicate when qbox should execute commands in the input file (http://qboxcode.org/doc/html/usage/client-server.html).

Based on your description, this may indeed be due to the structure file you inputted.  The *xyz file format does not specify lattice parameters, which are needed in the DFT calculation; a straightforward thing to try would be to convert *xyz to *cif. You will want to make sure the inputted structures to qbox and pycdft are consistent with each other.

Also, for future reference, please open a new issue for new topics and mark whether the previous thread has been resolved.

**Comment by wwwennie** [comment]
closed issue
